Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "control-plane"
  config.vm.network "private_network", ip: "192.168.50.1"

  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.memory = 4096
    v.linked_clone = false
  end
  # Update repositories
  config.vm.provision "shell", path: "install.sh"
  # config.vm.provision "shell", path: "./scripts/common.sh"
end