apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels:
    app: busybox-container
spec:
  containers:
  - name: busybox-container
    image: ubuntu:22.04
    command:
      - sleep
      - "3600"
    tty: true
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: busy-svc
  name: busy-svc
spec:
  selector:
    app: busybox-container
  type: ClusterIP
  ports:
    - name: http
      targetPort: 80
      port: 80 
      protocol: TCP
