apiVersion: v1
kind: Pod
metadata:
  name: ephemeral-volume-exalple
  labels:
    name: ephemeral-volume-exalple
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "36000"
    volumeMounts:
      - name:  ephemeral-volume
        mountPath:  /test
  volumes:
    - name:  ephemeral-volume
      emptyDir: {}
# Dữ liệu tại kiểu này sẽ bị xóa đi khi Pod bị xóa (Lưu trữ Data tạm thời)
