apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: dev
  name: nginx-app-dev
spec:
  nodeName: worker-node02
  containers:
  - image: nginx
    name: nginx-app-dev
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
