apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: prod
  name: nginx-app-prod
spec:
  nodeSelector:
    kubernetes.io/hostname: worker-node02
  containers:
  - image: nginx
    name: nginx-app-prod
    resources: {}
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: env
                operator: NotIn
                values:
                - dev
          topologyKey: kubernetes.io/hostname
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
