apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web-app
  serviceName: "nginx-svc"
  replicas: 4
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-label
spec:
  clusterIP: None
  selector:
    app: web-app
  ports:
    - name: http 
      port: 80
      # targetPort: 80
