apiVersion: v1
kind: Pod
metadata:
  name: ephemeral-volume-exalple
  labels:
    name: ephemeral-volume-exalple
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name:  ephemeral-volume
        mountPath:  /test # Thư mục cần Mount của container
      - name:  ephemeral-volume2
        mountPath:  /test2 # Thư mục cần Mount của container
  volumes:
    - name:  ephemeral-volume
      emptyDir: {}
    - name:  ephemeral-volume2
      emptyDir: {}
# Dữ liệu tại kiểu này sẽ bị xóa đi khi Pod bị xóa (Lưu trữ Data tạm thời) Tức là nó sẽ đi theo Lifetime của Pod luôn