apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm
data:
  db_host: mysql-0.mysql-svc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  labels:
    app: nginx-cm
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
        listen      80;
        server_name localhost;
        location / {
          root    /usr/share/nginx/html;
          index   index.html index.html
        }
      }
    }
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name:  nginx-app-mount
            mountPath:  /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
      volumes:
        - name:  nginx-app-mount
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
