apiVersion: v1
kind: Pod
metadata:
  name: nginx-app-demo
  labels:
    name: nginx-app-demo
  namespace: default
spec:
  containers:
  - name: nginx-app-demo
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  # service account define
  serviceAccount: default-demo
