apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default-role-demo
  namespace: default
rules:
  - apiGroups: [""] # empty string represents the core API Group
    resources: ["pods","services"]
    verbs: ["get","list","watch","apply"]
  - apiGroups: ["apps"]
    resources: ["deployment"]
    verbs: ["get","list"]

---
# Khi define xong Role thì ta sẽ gán nó để có thể sử dụng với RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-rolebinding
  namespace: default
subjects:
  - namespace: default
    kind: ServiceAccount
    name: default # các thành phần sử dụng ServiceAccount là default
roleRef:
  kind: Role
  name: default-role-demo
  apiGroup: rbac.authorization.k8s.io

# TEST API SERVER
# Trước hết ta nên export ENV chứa các cert
# export SERVICE_ACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
# export CA_CERT=${SERVICE_ACCOUNT}/ca.crt
# export TOKEN=`cat ${SERVICE_ACCOUNT}/token`
# curl --cacert ${CA_CERT} --header "Authorization: Bearer ${TOKEN}" \
#  -X GET https://kubernetes.default.svc/api/v1/namespaces/default/pods

