apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 1 # Max là 1 Pod tắt tại 1 thời điểm
      maxSurge: 1 # Chỉ có 1 Pod tạo ra tại thời điểm đó
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
