apiVersion: v1
kind: Pod
metadata:
  name: ephemeral-volume-exalple
  labels:
    name: ephemeral-volume-exalple
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
      - name:  host-path
        mountPath:  /usr/share/nginx/html/test.html
        subPath: test.html 
  volumes:
    - name:  host-path
      hostPath:
        path:  /data
        type: Directory
# Trước tiên tại Node ta muốn tạo cần phải defined folder và file /data/test.html thì từ đó ta có thể Mount được data từ folder ngoài vào đường dẫn bên trong container
# mkdir data
# echo 'Hello world' > /data/test.html
# Dữ liệu tại đây sẽ được lưu ngay tại Node nơi mà Pod được tạo ra 
# Đường dẫn Mount data mình phải tự tạo