apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  labels: 
    app: stateful-set-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  serviceName: "nginx-svc" # Service Name defined phải match với Headless Service ở dưới
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc # Service Name defined phải match với Headless Service ở trên
  labels:
    app: nginx-svc
spec:
  clusterIP: None
  selector:
    app: nginx-app
  ports:
  - name: http
    port: 80
    # targetPort: 80